@startuml
' Family Arborescence Gari

skinparam defaultFontName Arial
skinparam rectangle {
  BackgroundColor #FDF6E3
  BorderColor #657B83
  FontColor #586E75
}
' Slimen Family
rectangle "Slimen Gari\n(1953-)" as Slimen
rectangle "Meska Bouhstine\n(1953-)" as Meska
Slimen =right= Meska
Slimen -- MSM
Meska -- MSM


' Laroussi Family
rectangle "Laroussi Gari\n(1953-)" as Laroussi
MSM -- Laroussi
rectangle "Rachida gari\n(1954-2020)" as Rachida
rectangle "Yasmina\n(XXXX-)" as Yasmina
Laroussi =left= Rachida
Laroussi -- MLR
Rachida -- MLR
Laroussi =right= Yasmina
Laroussi -- MLY
Yasmina -- MLY

rectangle "Khaled Gari\n(1987-)" as Khaled
rectangle "Nesrine Gari\n(1987-)" as Nesrine
rectangle "Walid Gari\n(1987-)" as Walid
rectangle "Jihen Gari\n(1987-)" as Jihen

MLR -- Khaled
MLR -- Nesrine
MLR -- Walid
MLR -- Jihen

' Huerguel Family
rectangle "Mohamed Huerguel\n(1987-)" as MohamedH
MohamedH =left= Nesrine
rectangle "Aziz Huerguel\n(2014-)" as Aziz
rectangle "Ghali Huerguel\n(2014-)" as Ghali
rectangle "Jouri Huerguel\n(2014-)" as Jouri
MohamedH -- MMN
Nesrine -- MMN
MMN -- Aziz
MMN -- Ghali
MMN -- Jouri

' Walid Gari Family
rectangle "Wejden Khaloui\n(1987-)" as Wejden
Walid =left= Wejden
rectangle "Hamza Gari\n(2014-)" as Hamza
rectangle "Ahmed Gari\n(2014-)" as Ahmed
rectangle "Joud Gari\n(2014-)" as Joud
Walid -- MWW
Wejden -- MWW
MWW -- Hamza
MWW -- Ahmed
MWW -- Joud

' Fadhel Family
rectangle "Fadhel Ferjani\n(1987-)" as Fadhel
Fadhel =left= Jihen
Fadhel -- MFJ
Jihen -- MFJ
@enduml
